### ISSUE TITLE
Cover position undefined in Home Assistant after upgrade from 0.30 to 0.34.1

### ISSUE THREAD

**Issue by dhzl84** [gluap/pyduofern#25]
Hello gluap,

I use the custom component for Home Assistant since quite some time and it was rock solid until the switching to 0.34.1.
I did not change anything than replacing the _duofern_ folder in _custom_components_.

Home Assistant throws this warning at me, but I have no clue how to fix it.

```
Logger: /usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py
Source: /usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py:597
First occurred: 9:48:55 PM (1 occurrences)
Last logged: 9:48:55 PM

update_callback() missing 3 required positional arguments: 'id', 'key', and 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 595, in run
    self.process_message(in_data)
  File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern_stick.py", line 227, in process_message
    self.duofern_parser.parse(message)
  File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 203, in parse
    self.update_state(code, "version", ver, "0", channel=channel)
  File "/usr/local/lib/python3.8/site-packages/pyduofern/duofern.py", line 128, in update_state
    self.changes_callback()
TypeError: update_callback() missing 3 required positional arguments: 'id', 'key', and 'value'
```

Hope you'll find some time to look into that, I'll revert to 0.30 for now.

Thank you in advance!

**Comment by DomiStyle** [comment]
This should be fixed with #26 .

The custom component was still using the old library.

**Comment by gluap** [comment]
I merged #26 and it should indeed fix the issue. I had overlooked the version lock in the json file and only updated the old style dependency in ``__init__.py``. Thanks to @DomiStyle for finding and fixing this!

**Comment by dhzl84** [comment]
Tested with #26 and it works just fine. Thank you both!

**Comment by mmatesic01** [comment]
It works but it show oposite status. Status is open is when cover closed and closed when it is open.

**Comment by DomiStyle** [comment]
@gluap @mmatesic01 Should be fixed with https://github.com/gluap/pyduofern/pull/27
